"""Per-signal statistics recorder for Ayumi trading system.

Supports SRB-AYU-002 (feature drift monitoring) and SRB-AYU-003
(confluence-score validation) by recording every {signal, outcome} pair
generated by the forward test, and exposing aggregated queries.

Storage format: newline-delimited JSON (JSONL). Each signal may produce up
to two lines: one at open time (``record_signal``) and one at close time
(``record_outcome``). The two lines are correlated via ``signal_id``.

Atomicity: every write goes through a temp file + ``os.replace`` to avoid
torn writes if the process is killed mid-write. Concurrent writers are
serialised with a single ``threading.Lock`` so the JSONL invariant
(one JSON object per line) is preserved even under heavy contention.
"""

from __future__ import annotations

import json
import os
import threading
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# Outcome vocabulary. ``OPEN`` is a sentinel used internally for lines
# written by ``record_signal`` (no outcome yet) so consumers can tell
# "open" apart from "close" without inspecting field nulls.
_OPEN = "open"

# Valid outcome states for closed positions. ``OPEN`` is reserved for
# the initial record-signal line and is never passed to record_outcome.
VALID_OUTCOMES = {
    "tp_hit",
    "sl_hit",
    "manual_close",
    "expired",
    "timeout_close",
    "rejected",
}


@dataclass
class SignalRecord:
    """One row of the signal-stats log.

    ``outcome`` and the four outcome-related fields are populated when
    the position closes (a second line is written to the JSONL with the
    same ``signal_id``). The first line always has ``outcome == "open"``.
    """

    signal_id: str
    timestamp: str
    strategy: str
    symbol: str
    direction: str  # "BUY" | "SELL" (string form of TradeDirection)
    confidence: float
    rationale_tags: list[str] = field(default_factory=list)
    confluence_score: float = 0.0
    lots: float = 0.0
    entry_price: float = 0.0
    sl_price: float = 0.0
    tp_price: float = 0.0

    # Outcome fields — None on the open line, populated on the close line.
    outcome: Optional[str] = None
    pips_realized: Optional[float] = None
    time_to_close_seconds: Optional[int] = None
    closed_at: Optional[str] = None

    # Rejection fields — populated only when outcome == "rejected".
    rejection_reason: Optional[str] = None
    error_code: Optional[str] = None


class SignalStatsRecorder:
    """Append-only JSONL recorder for {signal, outcome} pairs.

    Thread-safe: a single ``threading.RLock`` serialises all writes.
    Multiple strategies can record concurrently without corrupting the
    JSONL format (one JSON object per line, always terminated by ``\\n``).

    Reads (``get_stats``) are best-effort snapshots of the file at call
    time and are not protected against a writer that is mid-append. In
    practice this is fine because each line is a self-contained JSON
    object written atomically; a partial last line either parses or
    raises ``json.JSONDecodeError`` which we catch and skip.
    """

    def __init__(self, log_path: str = "data/signal_stats.jsonl"):
        self.log_path = log_path
        # RLock so record_outcome() can call _append_line() (which takes
        # the lock) from inside its own critical section. A plain Lock
        # would deadlock on the second acquire from the same thread.
        self._lock = threading.RLock()
        # Ensure parent dir exists so the first record_signal() succeeds
        # even when called from a fresh checkout / test sandbox.
        parent = Path(log_path).expanduser().resolve().parent
        if str(parent) and str(parent) != ".":
            parent.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Write API
    # ------------------------------------------------------------------

    def record_signal(self, record: SignalRecord) -> str:
        """Append the open line for a new signal. Returns ``signal_id``."""
        # Defensive: normalise outcome to OPEN on the first line so we
        # never persist a partially-populated close record by accident.
        if record.outcome is None:
            record.outcome = _OPEN
        if not record.signal_id:
            record.signal_id = str(uuid.uuid4())
        if not record.timestamp:
            record.timestamp = datetime.now(timezone.utc).isoformat()

        self._append_line(asdict(record))
        return record.signal_id

    def record_outcome(
        self,
        signal_id: str,
        outcome: str,
        pips: float,
        time_to_close: int,
    ) -> None:
        """Append a close line for an existing signal.

        The open line is *not* modified — outcome data lives in a second
        row so the original signal snapshot is preserved for auditing.
        If no open row is found the close row is still written (a warning
        is emitted) so we never silently drop an outcome.
        """
        if outcome not in VALID_OUTCOMES:
            raise ValueError(f"Invalid outcome {outcome!r}; expected one of {sorted(VALID_OUTCOMES)}")

        with self._lock:
            existing = self._find_open_line(signal_id)
            if existing is None:
                # Close arrived without an open record (engine restart,
                # signal generated before this recorder was attached, or
                # a manual replay). Persist a minimal close row using
                # whatever metadata survived from prior close lines, or
                # fall back to placeholders.
                existing = self._find_any_line(signal_id) or {}

            close_record = {
                "signal_id": signal_id,
                "timestamp": existing.get("timestamp", ""),
                "strategy": existing.get("strategy", "unknown"),
                "symbol": existing.get("symbol", "unknown"),
                "direction": existing.get("direction", ""),
                "confidence": existing.get("confidence", 0.0),
                "rationale_tags": existing.get("rationale_tags", []),
                "confluence_score": existing.get("confluence_score", 0.0),
                "lots": existing.get("lots", 0.0),
                "entry_price": existing.get("entry_price", 0.0),
                "sl_price": existing.get("sl_price", 0.0),
                "tp_price": existing.get("tp_price", 0.0),
                "outcome": outcome,
                "pips_realized": float(pips),
                "time_to_close_seconds": int(time_to_close),
                "closed_at": datetime.now(timezone.utc).isoformat(),
            }
            # Append OUTSIDE the inner lookup but inside the lock for
            # atomicity with the read.
            self._append_line(close_record)

    def record_rejection(
        self,
        signal_id: str,
        rejection_reason: str,
        error_code: str = "",
    ) -> None:
        """Append a rejection outcome line for a signal.

        Rejections are recorded as a close line with ``outcome="rejected"``
        plus the broker's ``rejection_reason`` and ``error_code`` so the
        rejection rate is queryable alongside win/loss outcomes.
        """
        with self._lock:
            existing = self._find_open_line(signal_id)
            if existing is None:
                existing = self._find_any_line(signal_id) or {}

            rejection_record = {
                "signal_id": signal_id,
                "timestamp": existing.get("timestamp", ""),
                "strategy": existing.get("strategy", "unknown"),
                "symbol": existing.get("symbol", "unknown"),
                "direction": existing.get("direction", ""),
                "confidence": existing.get("confidence", 0.0),
                "rationale_tags": existing.get("rationale_tags", []),
                "confluence_score": existing.get("confluence_score", 0.0),
                "lots": existing.get("lots", 0.0),
                "entry_price": existing.get("entry_price", 0.0),
                "sl_price": existing.get("sl_price", 0.0),
                "tp_price": existing.get("tp_price", 0.0),
                "outcome": "rejected",
                "pips_realized": 0.0,
                "time_to_close_seconds": 0,
                "closed_at": datetime.now(timezone.utc).isoformat(),
                "rejection_reason": rejection_reason,
                "error_code": error_code,
            }
            self._append_line(rejection_record)

    # ------------------------------------------------------------------
    # Read API
    # ------------------------------------------------------------------

    def get_stats(
        self,
        strategy: Optional[str] = None,
        symbol: Optional[str] = None,
        since: Optional[str] = None,
    ) -> dict:
        """Return aggregated stats for signals matching the filters.

        A signal is "closed" iff we have a close line whose ``outcome``
        is one of ``VALID_OUTCOMES``. Open lines do not contribute to
        hit rate / avg pips but they do count toward ``total_signals``.

        Filters:
            strategy — exact match on ``strategy`` field.
            symbol   — exact match on ``symbol`` field.
            since    — ISO-8601 timestamp string; only signals whose open
                       timestamp is >= ``since`` are included.
        """
        rows = self._read_all_rows()

        # Build per-signal latest-state view: for each signal_id keep
        # the open line plus any close line. We use a dict so the most
        # recent write wins (close overrides open for outcome fields).
        signals: dict[str, dict] = {}
        for row in rows:
            sid = row.get("signal_id")
            if not sid:
                continue
            signals[sid] = {**signals.get(sid, {}), **row}

        # Apply filters based on the signal's open metadata.
        def keep(rec: dict) -> bool:
            if strategy is not None and rec.get("strategy") != strategy:
                return False
            if symbol is not None and rec.get("symbol") != symbol:
                return False
            if since is not None:
                ts = rec.get("timestamp", "")
                if ts and ts < since:
                    return False
            return True

        filtered = [r for r in signals.values() if keep(r)]
        closed = [r for r in filtered if r.get("outcome") in VALID_OUTCOMES]
        wins = [r for r in closed if r.get("outcome") == "tp_hit"]
        rejections = [r for r in closed if r.get("outcome") == "rejected"]

        # Per-strategy / per-symbol breakdowns (always computed so the
        # dashboard can chart even when no filter is active).
        by_strategy: dict[str, int] = {}
        by_symbol: dict[str, int] = {}
        for rec in filtered:
            s = rec.get("strategy") or "unknown"
            sym = rec.get("symbol") or "unknown"
            by_strategy[s] = by_strategy.get(s, 0) + 1
            by_symbol[sym] = by_symbol.get(sym, 0) + 1

        # Average time-to-close (seconds) over closed records.
        time_to_close_values = [
            int(r["time_to_close_seconds"]) for r in closed if r.get("time_to_close_seconds") is not None
        ]
        avg_time_to_close = sum(time_to_close_values) / len(time_to_close_values) if time_to_close_values else 0.0

        # Average pips over closed records.
        pips_values = [float(r["pips_realized"]) for r in closed if r.get("pips_realized") is not None]
        avg_pips = sum(pips_values) / len(pips_values) if pips_values else 0.0

        return {
            "total_signals": len(filtered),
            "open_signals": len(filtered) - len(closed),
            "closed_signals": len(closed),
            "wins": len(wins),
            "losses": len(closed) - len(wins) - len(rejections),
            "rejections": len(rejections),
            "rejection_rate": (len(rejections) / len(closed) if closed else 0.0),
            "hit_rate": (len(wins) / len(closed)) if closed else 0.0,
            "avg_pips": avg_pips,
            "avg_time_to_close_seconds": avg_time_to_close,
            "by_strategy": by_strategy,
            "by_symbol": by_symbol,
            "filters": {
                "strategy": strategy,
                "symbol": symbol,
                "since": since,
            },
        }

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _append_line(self, payload: dict) -> None:
        """Atomic append: read existing content, concatenate the new
        line, write to a sibling temp file, then ``os.replace`` onto
        the target. Honours both the JSONL append-only invariant and
        the spec's "temp + rename" atomicity requirement.

        Cost is O(file size) per write. Acceptable for a per-signal
        stats log (low write rate; reads are aggregated out-of-band).
        """
        import tempfile

        line = json.dumps(payload, default=str) + "\n"
        target = Path(self.log_path)
        target_parent = target.parent
        target_parent.mkdir(parents=True, exist_ok=True)

        with self._lock:
            # Read existing content (if any). Use bytes mode so we
            # don't have to worry about newline normalisation between
            # platforms — we always append "\n".
            if target.exists():
                with open(target, "rb") as f:
                    existing = f.read()
            else:
                existing = b""

            new_bytes = existing + line.encode("utf-8")

            fd, tmp_path = tempfile.mkstemp(
                dir=str(target_parent),
                prefix=".signal_stats.",
                suffix=".tmp",
            )
            try:
                with os.fdopen(fd, "wb") as f:
                    f.write(new_bytes)
                    f.flush()
                    try:
                        os.fsync(f.fileno())
                    except OSError:
                        # fsync may be unsupported on tmpfs / certain
                        # sandboxed filesystems. The data is already
                        # in the OS write buffer, so fall through.
                        pass
                    # tempfile.mkstemp creates files with mode 0600; that
                    # mode would carry over via os.replace and lock out
                    # any other uid (e.g. forward-test running as uid 1000
                    # after a root-run service restart left a 0600 file
                    # behind). fchmod the temp fd to 0o644 inside the
                    # with-block (fd still valid) so the eventual target
                    # is group/other readable. Guarded so a chmod failure
                    # cannot lose the write — bytes are already on disk.
                    try:
                        os.fchmod(fd, 0o644)
                    except (OSError, AttributeError):
                        # AttributeError on Windows; OSError on
                        # filesystems without chmod support. Either way,
                        # the data is safe and the replace proceeds.
                        pass
                os.replace(tmp_path, str(target))
                # Self-heal: if the target ended up with restrictive
                # mode (e.g. a root-owned file from a prior service
                # restart left behind 0600), chmod it back to 0o644 so
                # subsequent writers (uid 1000) can append. Guarded so
                # a chmod failure never raises — the data is already
                # on disk and the write succeeded.
                try:
                    target_st = os.stat(str(target))
                    if (target_st.st_mode & 0o777) != 0o644:
                        os.chmod(str(target), 0o644)
                except OSError:
                    pass
            except Exception:
                try:
                    os.unlink(tmp_path)
                except OSError:
                    pass
                raise

    def _find_open_line(self, signal_id: str) -> Optional[dict]:
        """Return the first OPEN line for ``signal_id`` (most recent
        winning line by append order)."""
        rows = self._read_all_rows()
        for row in rows:
            if row.get("signal_id") == signal_id and row.get("outcome") in (
                None,
                _OPEN,
            ):
                return row
        return None

    def _find_any_line(self, signal_id: str) -> Optional[dict]:
        rows = self._read_all_rows()
        for row in rows:
            if row.get("signal_id") == signal_id:
                return row
        return None

    def _read_all_rows(self) -> list[dict]:
        """Read every parseable line from the JSONL log.

        Tolerant of partial last lines (mid-write crash): a line that
        fails to parse is silently dropped. Returns [] if the file
        does not exist.
        """
        path = Path(self.log_path)
        if not path.exists():
            return []
        out: list[dict] = []
        try:
            with open(path, "r", encoding="utf-8") as f:
                for raw in f:
                    line = raw.strip()
                    if not line:
                        continue
                    try:
                        out.append(json.loads(line))
                    except json.JSONDecodeError:
                        # Tolerate a torn trailing line.
                        continue
        except OSError:
            return out
        return out


__all__ = [
    "SignalRecord",
    "SignalStatsRecorder",
    "VALID_OUTCOMES",
]


# ------------------------------------------------------------------
# Self-test (AC3: verifies rejected orders appear in stats)
# Run: python3 -m pytest signal_engine/signal_stats.py::test_rejection_recording
# Or:  python3 -c "from signal_engine.signal_stats import test_rejection_recording; test_rejection_recording()"
# ------------------------------------------------------------------


def test_rejection_recording(tmp_path=None):
    """Verify that rejected orders are recorded in stats with rejection metadata."""
    import os
    import tempfile

    tmpdir = tmp_path or tempfile.mkdtemp()
    log_path = os.path.join(str(tmpdir), "test_signal_stats.jsonl")
    recorder = SignalStatsRecorder(log_path=log_path)

    # Record a normal signal (open line)
    sig_id = recorder.record_signal(  # noqa: F841 — live signal recording: write side-effect preserved
        SignalRecord(
            signal_id="test-sig-001",
            timestamp="2026-07-16T12:00:00Z",
            strategy="test_strategy",
            symbol="GBPUSD",
            direction="BUY",
            confidence=0.75,
        )
    )

    # Record a rejection outcome
    recorder.record_rejection(
        signal_id="test-sig-001",
        rejection_reason="NOT_ENOUGH_MONEY",
        error_code="INSUFFICIENT_FUNDS",
    )

    # Record a second signal that fills normally
    recorder.record_signal(
        SignalRecord(
            signal_id="test-sig-002",
            timestamp="2026-07-16T12:01:00Z",
            strategy="test_strategy",
            symbol="GBPUSD",
            direction="SELL",
            confidence=0.65,
        )
    )
    recorder.record_outcome("test-sig-002", "tp_hit", pips=25.0, time_to_close=3600)

    # Verify stats
    stats = recorder.get_stats()
    assert stats["total_signals"] == 2, (  # noqa: S101 — self-test invariant in `test_rejection_recording()`; debug-only result check, intentionally silenced under `python -O`
        f"Expected 2 signals, got {stats['total_signals']}"
    )
    assert stats["closed_signals"] == 2, (  # noqa: S101 — self-test invariant; debug-only result check, intentionally silenced under `python -O`
        f"Expected 2 closed, got {stats['closed_signals']}"
    )
    assert stats["rejections"] == 1, f"Expected 1 rejection, got {stats['rejections']}"  # noqa: S101 — self-test invariant; debug-only result check, intentionally silenced under `python -O`
    assert stats["rejection_rate"] == 0.5, (  # noqa: S101 — self-test invariant; debug-only result check, intentionally silenced under `python -O`
        f"Expected 0.5 rejection rate, got {stats['rejection_rate']}"
    )

    # Verify rejection metadata is persisted in the JSONL
    rows = recorder._read_all_rows()
    rejection_rows = [r for r in rows if r.get("outcome") == "rejected"]
    assert len(rejection_rows) == 1, (  # noqa: S101 — self-test invariant; debug-only row-count check, intentionally silenced under `python -O`
        f"Expected 1 rejection row, got {len(rejection_rows)}"
    )
    assert rejection_rows[0]["rejection_reason"] == "NOT_ENOUGH_MONEY"  # noqa: S101 — self-test invariant; debug-only column check, intentionally silenced under `python -O`
    assert rejection_rows[0]["error_code"] == "INSUFFICIENT_FUNDS"  # noqa: S101 — self-test invariant; debug-only column check, intentionally silenced under `python -O`

    # Cleanup
    if tmp_path is None:
        os.remove(log_path)

    print("test_rejection_recording: PASS")
