"""Synthetic regime generator — core GMM+HMM fitting + synthetic returns.

Fits a Gaussian Mixture Model (GMM) to log-returns to identify distributional
regimes, then fits a Hidden Markov Model (HMM) to capture regime transition
dynamics.  Synthetic return paths are generated by sampling from the fitted
distributions according to the HMM transition matrix.

Public API
----------
- :class:`RegimeParams` – fitted parameters from a single series
- :func:`fit_gmm_returns` – GMM fit to log-returns
- :func:`fit_hmm_returns` – HMM fit to GMM component labels
- :func:`bootstrap_synthetic_returns` – full pipeline: fit + generate
- :func:`regime_sequence_to_returns` – draw returns from regime sequence
- :func:`synthesize_prices` – cumulative-product price path from returns

The module is designed to be imported by ``regime_cli.py`` (child card) which
adds CSV I/O, ``run_all_pairs``, and command-line plumbing.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Sequence

import numpy as np
from hmmlearn.hmm import GaussianHMM
from sklearn.mixture import GaussianMixture

logger = logging.getLogger(__name__)

# ── Defaults ──────────────────────────────────────────────────────────────
DEFAULT_N_REGIMES = 3
DEFAULT_N_PATHS = 10_000
DEFAULT_RANDOM_STATE = 42
MIN_OBSERVATIONS = 100


# ═══════════════════════════════════════════════════════════════════════════
# Data structures
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class RegimeParams:
    """Fitted parameters from GMM+HMM regime estimation.

    Attributes
    ----------
    means : ndarray, shape (n_regimes,)
        Mean log-return for each regime.
    stds : ndarray, shape (n_regimes,)
        Std-dev of log-return for each regime.
    weights : ndarray, shape (n_regimes,)
        Stationary probability of each regime (GMM mixture weights).
    transmat : ndarray, shape (n_regimes, n_regimes)
        HMM transition probability matrix.
    startprob : ndarray, shape (n_regimes,)
        HMM initial state distribution.
    n_regimes : int
        Number of regimes fitted.
    bic : float
        Bayesian Information Criterion of the GMM fit (lower is better).
    """

    means: np.ndarray
    stds: np.ndarray
    weights: np.ndarray
    transmat: np.ndarray
    startprob: np.ndarray
    n_regimes: int
    bic: float

    def __post_init__(self) -> None:
        """Validate array shapes and value ranges."""
        n = self.n_regimes
        if self.means.shape != (n,):
            raise ValueError(f"means must have shape ({n},), got {self.means.shape}")
        if self.stds.shape != (n,):
            raise ValueError(f"stds must have shape ({n},), got {self.stds.shape}")
        if self.weights.shape != (n,):
            raise ValueError(f"weights must have shape ({n},), got {self.weights.shape}")
        if self.transmat.shape != (n, n):
            raise ValueError(f"transmat must have shape ({n},{n}), got {self.transmat.shape}")
        if self.startprob.shape != (n,):
            raise ValueError(f"startprob must have shape ({n},), got {self.startprob.shape}")
        # Stds must be positive
        if np.any(self.stds <= 0):
            raise ValueError("All stds must be positive")
        # Weights sum ~ 1
        if not np.isclose(self.weights.sum(), 1.0, atol=1e-6):
            raise ValueError(f"weights must sum to 1, got {self.weights.sum()}")
        # Each transmat row sums to 1
        row_sums = self.transmat.sum(axis=1)
        if not np.allclose(row_sums, 1.0, atol=1e-6):
            raise ValueError(f"transmat rows must sum to 1, got {row_sums}")
        # startprob sums to 1
        if not np.isclose(self.startprob.sum(), 1.0, atol=1e-6):
            raise ValueError(f"startprob must sum to 1, got {self.startprob.sum()}")


# ═══════════════════════════════════════════════════════════════════════════
# Fitting
# ═══════════════════════════════════════════════════════════════════════════


def _to_log_returns(prices: np.ndarray | Sequence[float]) -> np.ndarray:
    """Convert price array to log-returns.

    Parameters
    ----------
    prices : array-like
        1-D sequence of strictly positive prices.

    Returns
    -------
    ndarray
        Log-returns, shape ``(len(prices) - 1,)``.

    Raises
    ------
    ValueError
        If *prices* has fewer than 2 elements or contains non-positive values.
    """
    arr = np.asarray(prices, dtype=float).ravel()
    if arr.size < 2:
        raise ValueError(f"Need at least 2 prices, got {arr.size}")
    if np.any(arr <= 0):
        raise ValueError("All prices must be strictly positive")
    return np.diff(np.log(arr))


def fit_gmm_returns(
    returns: np.ndarray,
    n_regimes: int = DEFAULT_N_REGIMES,
    random_state: int = DEFAULT_RANDOM_STATE,
) -> tuple[GaussianMixture, float]:
    """Fit a Gaussian Mixture Model to log-returns.

    Parameters
    ----------
    returns : ndarray, shape (n,)
        1-D array of log-returns.
    n_regimes : int
        Number of mixture components (regimes).
    random_state : int
        Seed for reproducibility.

    Returns
    -------
    gmm : GaussianMixture
        Fitted sklearn GMM (sorted by component mean).
    bic : float
        Bayesian Information Criterion of the fit.

    Raises
    ------
    ValueError
        If *returns* has fewer than :data:`MIN_OBSERVATIONS` samples.
    """
    arr = np.asarray(returns, dtype=float).ravel()
    if arr.size < MIN_OBSERVATIONS:
        raise ValueError(f"Need at least {MIN_OBSERVATIONS} returns for reliable fit, got {arr.size}")
    if n_regimes < 1:
        raise ValueError(f"n_regimes must be >= 1, got {n_regimes}")

    X = arr.reshape(-1, 1)
    gmm = GaussianMixture(
        n_components=n_regimes,
        covariance_type="full",
        random_state=random_state,
        max_iter=500,
        n_init=3,
    )
    gmm.fit(X)

    # Sort components by mean for stable, interpretable regimes
    order = np.argsort(gmm.means_.ravel())
    gmm.means_ = gmm.means_[order]
    gmm.covariances_ = gmm.covariances_[order]
    gmm.weights_ = gmm.weights_[order]

    bic = float(gmm.bic(X))
    logger.debug(
        "GMM fit: %d regimes, BIC=%.2f, means=%s",
        n_regimes,
        bic,
        gmm.means_.ravel(),
    )
    return gmm, bic


def fit_hmm_returns(
    returns: np.ndarray,
    component_labels: np.ndarray,
    n_regimes: int,
    random_state: int = DEFAULT_RANDOM_STATE,
) -> GaussianHMM:
    """Fit a Gaussian HMM on returns conditioned on GMM component labels.

    The HMM captures temporal persistence of regimes (e.g. trending vs.
    mean-reverting vs. volatile periods).

    Parameters
    ----------
    returns : ndarray, shape (n,)
        Original log-returns used for emission fitting.
    component_labels : ndarray, shape (n,)
        Integer labels from the GMM fit, used to warm-start HMM parameters.
    n_regimes : int
        Number of hidden states (must match GMM components).
    random_state : int
        Seed for reproducibility.

    Returns
    -------
    hmm : GaussianHMM
        Fitted HMM with ``n_regimes`` states.
    """
    arr = np.asarray(returns, dtype=float).ravel().reshape(-1, 1)
    labels = np.asarray(component_labels, dtype=int).ravel()
    if arr.shape[0] != labels.shape[0]:
        raise ValueError(f"returns ({arr.shape[0]}) and labels ({labels.shape[0]}) must have same length")

    hmm = GaussianHMM(
        n_components=n_regimes,
        covariance_type="full",
        n_iter=500,
        random_state=random_state,
        tol=1e-4,
    )

    # Initialise means / covars from GMM labels for faster convergence
    means_init = np.zeros((n_regimes, 1))
    for k in range(n_regimes):
        mask = labels == k
        if mask.any():
            means_init[k, 0] = arr[mask].mean()
    hmm.start_params = ""
    hmm.transmat_prior = 1.0
    hmm.init_params = "stmc"  # re-estimate everything but with warm data
    hmm.fit(arr, lengths=None)

    logger.debug(
        "HMM fit: %d states, transmat diag=%s",
        n_regimes,
        np.diag(hmm.transmat_).round(4),
    )
    return hmm


# ═══════════════════════════════════════════════════════════════════════════
# Synthetic generation
# ═══════════════════════════════════════════════════════════════════════════


def _sample_regime_sequence(
    transmat: np.ndarray,
    startprob: np.ndarray,
    length: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """Draw a regime state path from the HMM transition matrix.

    Parameters
    ----------
    transmat : ndarray, shape (n, n)
        Row-stochastic transition matrix.
    startprob : ndarray, shape (n,)
        Initial state distribution.
    length : int
        Number of time-steps to generate.
    rng : numpy.random.Generator
        Random number generator.

    Returns
    -------
    ndarray, shape (length,)
        Integer regime labels in ``[0, n)``.
    """
    n = transmat.shape[0]
    states = np.empty(length, dtype=int)
    states[0] = rng.choice(n, p=startprob)
    for t in range(1, length):
        states[t] = rng.choice(n, p=transmat[states[t - 1]])
    return states


def regime_sequence_to_returns(
    states: np.ndarray,
    means: np.ndarray,
    stds: np.ndarray,
    rng: np.random.Generator,
) -> np.ndarray:
    """Convert a regime state sequence to log-returns.

    For each time-step the return is drawn from
    ``Normal(mean[state], std[state])``.

    Parameters
    ----------
    states : ndarray, shape (T,)
        Integer regime labels.
    means : ndarray, shape (n_regimes,)
        Per-regime mean log-return.
    stds : ndarray, shape (n_regimes,)
        Per-regime std-dev.
    rng : numpy.random.Generator
        Random number generator.

    Returns
    -------
    ndarray, shape (T,)
        Synthetic log-returns.
    """
    states_arr = np.asarray(states, dtype=int)
    return rng.normal(loc=means[states_arr], scale=stds[states_arr])


def synthesize_prices(
    log_returns: np.ndarray,
    start_price: float = 1.0,
) -> np.ndarray:
    """Convert synthetic log-returns to a price path.

    ``price[t] = start_price * exp(cumsum(log_returns[:t]))``

    Parameters
    ----------
    log_returns : ndarray, shape (T,)
        Synthetic log-returns.
    start_price : float
        Initial price (must be > 0).

    Returns
    -------
    ndarray, shape (T + 1,)
        Synthetic price path including the initial price.

    Raises
    ------
    ValueError
        If *start_price* is not positive.
    """
    if start_price <= 0:
        raise ValueError(f"start_price must be positive, got {start_price}")
    lr = np.asarray(log_returns, dtype=float).ravel()
    cum = np.cumsum(lr)
    return start_price * np.exp(np.concatenate([[0.0], cum]))


# ═══════════════════════════════════════════════════════════════════════════
# Full pipeline
# ═══════════════════════════════════════════════════════════════════════════


def bootstrap_synthetic_returns(
    prices: np.ndarray | Sequence[float],
    n_regimes: int = DEFAULT_N_REGIMES,
    n_paths: int = DEFAULT_N_PATHS,
    path_length: int | None = None,
    random_state: int = DEFAULT_RANDOM_STATE,
) -> tuple[np.ndarray, RegimeParams]:
    """End-to-end regime fitting + synthetic path generation.

    Fits GMM+HMM on the log-returns of *prices*, then generates
    *n_paths* synthetic return paths.

    Parameters
    ----------
    prices : array-like
        1-D price series used for fitting.
    n_regimes : int
        Number of GMM/HMM regimes.
    n_paths : int
        Number of synthetic paths to generate.
    path_length : int or None
        Length of each synthetic path.  If ``None``, uses the length of
        the input return series.
    random_state : int
        Seed for reproducibility.

    Returns
    -------
    synthetic_returns : ndarray, shape (n_paths, T)
        Synthetic log-return paths.
    params : RegimeParams
        Fitted regime parameters.

    Raises
    ------
    ValueError
        If the price series is too short for fitting.
    """
    returns = _to_log_returns(prices)
    if returns.size < MIN_OBSERVATIONS:
        raise ValueError(f"Price series too short: {returns.size} returns < {MIN_OBSERVATIONS} minimum")

    T = path_length if path_length is not None else returns.size
    rng = np.random.default_rng(random_state)

    # ── GMM ────────────────────────────────────────────────────────────
    gmm, bic = fit_gmm_returns(returns, n_regimes=n_regimes, random_state=random_state)
    component_labels = gmm.predict(returns.reshape(-1, 1))

    means = gmm.means_.ravel().copy()
    # Extract per-component std from the full covariance matrices
    stds = np.sqrt(np.sqrt(gmm.covariances_.ravel()) ** 2).copy()
    # gmm.covariances_ for covariance_type="full" has shape (n, 1, 1)
    # → squeeze to (n,) for 1-D data
    stds = np.sqrt(gmm.covariances_.reshape(n_regimes, -1)[:, 0]).copy()
    weights = gmm.weights_.ravel().copy()

    # ── HMM ────────────────────────────────────────────────────────────
    hmm = fit_hmm_returns(returns, component_labels, n_regimes, random_state=random_state)
    transmat = hmm.transmat_.copy()
    startprob = hmm.startprob_.copy()

    params = RegimeParams(
        means=means,
        stds=stds,
        weights=weights,
        transmat=transmat,
        startprob=startprob,
        n_regimes=n_regimes,
        bic=bic,
    )

    # ── Generate synthetic paths ──────────────────────────────────────
    all_returns = np.empty((n_paths, T), dtype=float)
    for i in range(n_paths):
        states = _sample_regime_sequence(transmat, startprob, T, rng)
        all_returns[i] = regime_sequence_to_returns(states, means, stds, rng)

    logger.info(
        "Generated %d synthetic paths (T=%d, n_regimes=%d, BIC=%.2f)",
        n_paths,
        T,
        n_regimes,
        bic,
    )
    return all_returns, params
